{{/*
# Copyright 2020 The Magma Authors.

# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
*/}}

---
{{ include "orc8rlib.service" (list . "metricsd.service") -}}
---
{{ include "orc8rlib.headless-service" (list . "metricsd.headless-service") -}}
{{- define "metricsd.service" -}}
metadata:
  name: orc8r-metricsd
  labels:
    {{- with .Values.metricsd.service.labels }}
{{ toYaml . | indent 4}}
    {{- end}}
  {{- with .Values.metricsd.service.annotations }}
  annotations:
{{ toYaml . | indent 4}}
  {{- end }}
spec:
  selector:
    app.kubernetes.io/component: metricsd
  ports:
    - name: grpc
      port: 9180
      targetPort: 9084
    - name: http
      port: 8080
      targetPort: 10084
{{- end -}}
{{- define "metricsd.headless-service" -}}
metadata:
  name: orc8r-metricsd-headless
  labels:
    {{- with .Values.metricsd.service.labels }}
{{ toYaml . | indent 4}}
    {{- end}}
  {{- with .Values.metricsd.service.annotations }}
  annotations:
{{ toYaml . | indent 4}}
  {{- end }}
spec:
  selector:
    app.kubernetes.io/component: metricsd
  ports:
    - name: grpc
      port: 9084
      targetPort: 9084
    - name: http
      port: 10084
      targetPort: 10084
{{- end -}}
