---
name: "Workflow Cleanup"

on:
  push: null
  schedule:
    - cron: '42 0,6,12,18 * * *'

jobs:
  workflow-cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: Mattraks/delete-workflow-runs@v2.0.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          retain_days: 90
          keep_minimum_runs: 0
#          dry_run: true
